### ISSUE TITLE
[Question] spike hub to wedo 2.0

### ISSUE THREAD

**Issue by radu022003** [nutki/spike-tools#4]
hi, i have successfully connected over BLE a Lego Spike Hub and Lego WeDo 2.0.
Next step was to exchange some data between them, so i tried to change the WeDo 2.0 LED color.
Following the source code from this repo: https://github.com/nathankellenicki/node-poweredup , i could see that for setting the LED, 2 BLE Characteristics need to be used.
The question is, how to do this using the micropython on Spike hub? Since i saw that the send function of the connection object does not support the second parameter, the BLE Characteristic.

**Comment by nutki** [comment]
As far as I recall the BLE client implemented in the micropython firmware was specific to the current version of the LWP and as such unable to communicate with WeDo2. However this is based on the my own investigation as at the time I was not aware of any documentation of the Lego micropython fork. It is also based on the initial version of the Spike firmware, which may have since been updated.
I may revisit this project as I know now there is more python support in the official Lego Spike software.

**Comment by radu022003** [comment]
Thank you very much for detailed reply.
